---
- name: "Install Zed"
  community.general.homebrew_cask:
    name: zed
    state: present

- name: "Ensure Zed configuration directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/zed"
    state: directory
    mode: "0755"

- name: "Symlink Zed config files"
  ansible.builtin.file:
    src: "{{ local_config_root }}/editor/global/zed/{{ item.src }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/zed/{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: settings.json
      dest: settings.json
    - src: keymap.json
      dest: keymap.json
