---
- name: "Install Ghostty"
  community.general.homebrew_cask:
    name: ghostty
    state: present

- name: "Ensure Ghostty configuration directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/com.mitchellh.ghostty"
    state: directory
    mode: "0755"

- name: "Symlink Ghostty config"
  ansible.builtin.file:
    src: "{{ local_config_root }}/ghostty/global/config.ghostty"
    dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/com.mitchellh.ghostty/config.ghostty"
    state: link
    force: true
