## Xcode & Swift Development
brew "xcodes"
brew "xcbeautify"
brew "mint"

## PostgreSQL
brew "postgresql"

## Databases
brew "redis"

## Document
brew "poppler"
brew "pandoc"

## Modern Unix
brew "ripgrep"
brew "bat"
brew "eza"
brew "fd"

## CLI Tools
brew "yq"
brew "shellcheck"
brew "shfmt"
brew "mise"

## Media
brew "ffmpeg"