---
- name: "Install uv-managed Python version"
  ansible.builtin.command:
    cmd: "uv python install {{ python_version }} --default --no-progress"
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"
