---
- name: "Install uv"
  community.general.homebrew:
    name: uv
    state: present

- name: "Ensure .config/uv directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/uv"
    state: directory
    mode: "0755"

- name: "Symlink uv.toml"
  ansible.builtin.file:
    src: "{{ local_config_root }}/python/global/uv.toml"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/uv/uv.toml"
    state: link
    force: true
