name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.mock-*'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.mock-*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/run-linters.yml

  test:
    name: Test
    uses: ./.github/workflows/run-tests.yml

  coverage:
    name: Coverage
    uses: ./.github/workflows/collect-coverage.yml

  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
