name: Setup Python

on:
  workflow_call:

jobs:
  setup-python:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Run python-platform setup
        run: mise exec -- just run make python-platform

      - name: Run python-tools setup
        run: mise exec -- just run make python-tools
