name: Setup IDE

on:
  workflow_call:

jobs:
  setup-vscode:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup VSCode configuration
        run: mise exec -- just run make vscode

      - name: Setup Antigravity configuration
        run: mise exec -- just run make antigravity

      - name: Setup Cursor configuration
        run: mise exec -- just run make zed

      - name: Setup Xcode configuration
        run: mise exec -- just run make xcode
