name: Setup Go

on:
  workflow_call:

jobs:
  setup-go:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup go
        run: just run make go
